name: mobile_app
description: Workplace document scanner mobile app
publish_to: "none"
version: 1.1.2+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cunning_document_scanner: ^1.4.0
  dio: ^5.8.0+1
  firebase_core: ^4.6.0
  firebase_messaging: ^16.1.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  image: ^4.5.4
  intl: ^0.20.2
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.2
  uuid: ^4.5.1
  file_picker: ^10.1.9
  flutter_local_notifications: ^19.4.0
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  record: ^6.0.0
  just_audio: ^0.10.5
  package_info_plus: ^8.0.0
  gal: ^2.3.2
  connectivity_plus: ^7.1.0
  animated_emoji: ^3.2.1
  lottie: ^3.3.3
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animated_emoji_lottie/
    - assets/notification_sounds/default_tone.wav
    - assets/notification_sounds/chime_tone.wav
    - assets/notification_sounds/alert_tone.wav
