'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';
type Direction = 'rtl' | 'ltr';

interface LanguageContextProps {
  language: Language;
  dir: Direction;
  toggleLanguage: () => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    projects: 'Projects',
    aiChat: 'AI Chat',
    snippets: 'Snippets Library',
    errors: 'Errors Library',
    systems: 'Reusable Systems',
    developerDna: 'Developer DNA',
    timeMachine: 'Time Machine',
    team: 'Team Brain',
    billing: 'Billing & Plans',
    adminPanel: 'Admin Panel',
    profileSettings: 'Profile & Settings',
    logout: 'Logout',
    newProject: 'New Project',
    cloudStorage: 'Cloud Storage',
    searchMemory: 'Search memory...',
    intelligentDeveloperMemory: 'INTELLIGENT DEVELOPER MEMORY',
    switchLanguageTitle: 'Switch to Arabic',

    // General UI
    free: 'Free',
    pro: 'Pro',
    teamPlan: 'Team',
    upgradeBtn: 'Upgrade Now',
    cancel: 'Cancel',
    save: 'Save',
    loading: 'Loading...',
    settings: 'Settings',
    saveSuccess: 'Settings saved successfully!',
    errorOccurred: 'An error occurred.',
    
    // Dashboard & Spotlight
    welcomeBack: 'Welcome back',
    aiDailyStandup: 'AI Daily Standup',
    generateStandup: 'Generate Daily Report',
    hiddenKnowledge: 'Hidden Knowledge Finder',
    opportunityEngine: 'SaaS Opportunity Engine',
    activeAlerts: 'Active Alerts',
    recentProjects: 'Recent Projects',
    generic: 'Generic',
    vanilla: 'Vanilla',
    indexedFiles: 'Indexed Files',
    smartSnippets: 'Smart Snippets',
    solvedErrors: 'Solved Errors',
    reusableSystems: 'Systems',
    aiQueries: 'AI Queries',
    navDashboard: 'Pages / Dashboard',
    systemOverview: 'System Overview',
    searchPlaceholder: 'Search architecture and snippets...',
    welcomeUser: 'Welcome',
    dashboardSubtitle: 'This is the summary of your synced developer memory',
    developerDnaHealth: 'Developer DNA Health',
    indexedFromRepos: '↗ Indexed from active repositories',
    highEngineeringMemory: 'High Engineering Memory',
    activeProjects: 'Active Projects',
    searchEngineering: 'Search your engineering brain...',
    searchInstruction: 'Press ⌘K to search code, projects, or solutions.',
    projectHealth: 'Project Health',
    repoStatus: 'Live status of your repositories inside the vault',
    viewAll: 'View All',
    dailyDeveloperReport: 'Daily Developer Report',
    dailyReportDesc: 'Generate an AI-powered daily standup based on your recent activity.',
    generateReport: 'Generate Report',
    generatingReport: 'Generating report...',
    hiddenKnowledgeFinder: 'Hidden Knowledge Finder',
    hiddenKnowledgeDesc: 'Detect and avoid code duplication across your projects.',
    scanDuplicates: 'Scan for Duplicates',
    smartOpportunityEngine: 'Smart Opportunity Engine',
    opportunityDesc: 'Analyze your codebase to suggest potential SaaS business ideas.',
    generateSaaS: 'Generate SaaS Idea',
    recentActivityLog: 'Recent Activity Log',
    recentActivityDesc: 'Track changes and operations performed on your account',

    // New Dashboard specific translations
    dashboardWelcomeBack: 'Welcome Back',
    dashboardWelcomeUser: 'Welcome, {name}',
    dashboardHealthDna: 'Developer DNA Health',
    dashboardActiveProjects: 'Active Projects',
    dashboardAiInsights: 'AI Insights',
    dashboardSearchPlaceholder: 'Search your engineering brain...',
    dashboardSearchCommand: 'Press ⌘K to search code, projects, or solutions.',
    dashboardStatsProjects: 'Projects',
    dashboardStatsFiles: 'Indexed Files',
    dashboardStatsSnippets: 'Smart Snippets',
    dashboardStatsErrors: 'Solved Errors',
    dashboardStatsSystems: 'Systems',
    dashboardStatsQueries: 'AI Queries',
    dashboardProjectHealth: 'Project Health',
    dashboardRepoStatus: 'Live status of your repositories inside the vault',
    dashboardViewAll: 'View All',
    dashboardNoProjects: 'No projects uploaded yet. Upload a ZIP to begin indexing.',
    dashboardSmartSuggestion: 'Smart Suggestion: Reusable system detected',
    dashboardJWTNotice: 'We noticed you built similar JWT structures across multiple files. You can convert this into a reusable system to scaffold it rapidly in future services.',
    dashboardGenerateSystem: 'Generate Reusable System',
    dashboardActivityTitle: 'AI Activity',
    dashboardNoActivity: 'No recent activity. Upload a repository to start tracking.',
    dashboardOpenChat: 'Open AI Chat',
    dashboardDailyReport: 'Smart Daily Report',
    dashboardDailyReportDesc: 'Generate a daily status report summarizing recent uploads, new snippets, and resolved errors.',
    dashboardCopyReport: 'Copy Report',
    dashboardReportCopied: 'Report copied.',
    dashboardDailyStandup: 'Smart Daily Report',
    dashboardGenerateReport: 'Generate Report',
    dashboardGeneratingReport: 'Generating...',
    dashboardHiddenKnowledge: 'Discover Hidden Knowledge',
    dashboardHiddenKnowledgeDesc: 'AI scans codebase history to identify repetitive blocks and structures you might have forgotten.',
    dashboardNoRepeats: 'No duplicate patterns detected yet. Upload more repositories to compare.',
    dashboardOpportunityTitle: 'Opportunity Engine',
    dashboardOpportunityDesc: 'AI analyzes your tech strengths and project count to suggest sellable SaaS blueprints.',
    dashboardExportBlueprint: 'Export Blueprint',
    activitySystemLog: 'System Log',
    activityUploadProject: 'Upload Project',
    activitySnippetsLib: 'Snippets Library',
    activityErrorsLib: 'Errors Library',
    activityReusableSys: 'Reusable System',
    activityTimeNow: 'Just now',
    activityTimeDays: '{count} days ago',
    activityTimeHours: '{count} hours ago',
    activityTimeMins: '{count} minutes ago',
    activityUploadedRepo: 'Uploaded repository: {name}',
    
    // Profile & Settings
    profileTitle: 'Profile & Settings',
    profileSubtitle: 'Personalize your account details, notification settings, and themes.',
    personalInfo: 'Personal Information',
    security: 'Security & Protection',
    preferences: 'App Preferences',
    nameLabel: 'Full Name',
    emailLabel: 'Email Address',
    bioLabel: 'Bio / Job Title',
    avatarLabel: 'Avatar URL',
    avatarPresets: 'Choose a preset avatar',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    accentColor: 'Accent Color',
    accentBlue: 'Classic Blue',
    accentPurple: 'Royal Purple',
    accentAmber: 'Warm Gold',
    accentGreen: 'Emerald Green',
    notificationsTitle: 'Notification Preferences',
    emailNotifications: 'Weekly Email Summary',
    aiInsights: 'Weekly AI Code Insights',
    securityAlerts: 'Security Alerts & Plan Quotas',
    saveSettings: 'Save All Settings',
    updating: 'Updating...',
    joinedDate: 'Joined Date',
    currentPlan: 'Current Plan',
    storageUsed: 'Storage Used',
    limitExceededMsg: 'You have exceeded your plan limits. Please upgrade to continue.',
    loadingProfileSettings: 'Loading profile settings...',
    passwordUpdatedSuccess: 'Password updated successfully!',
    bioPlaceholder: 'e.g. Senior Software Engineer | Passionate about AI & System Architecture',
    passwordSecurityNote: 'Keep your account secure by periodically updating your password.',
    preferencesSubtitle: 'Customize your styling theme and visual notifications preferences.',
    weeklyEmailDesc: 'Receive a weekly developer activity log directly in your email.',
    aiInsightsDesc: 'Get suggestions regarding duplicate codebase logic and SaaS opportunities.',
    securityAlertsDesc: 'Warnings on leaked system secret keys and subscription limits.',
    billingQuotaDesc: 'Track your workspace resources consumption and plan boundaries.',
    needMoreResources: 'Need more workspace storage space or projects?',
    upgradeForHigherLimits: 'Upgrade to Pro or Team plan to unleash higher boundaries.',

    // Auth & Verify
    loginTitle: 'Login',
    enterMemory: 'Enter your developer memory',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    loginBtn: 'Login',
    orContinueWith: 'Or continue with',
    dontHaveAccount: "Don't have an account?",
    registerNow: 'Register Now',
    confirmEmail: 'Confirm Email',
    codeSentMsg: 'We sent a 6-digit verification code to',
    enterCodePlaceholder: 'Enter verification code',
    devCodeLabel: 'Developer Sandbox Code',
    confirmAndLoginBtn: 'Confirm & Login',
    resendCodeBtn: 'Resend Code',
    resendingCode: 'Sending...',
    backToLoginBtn: 'Back to Login',
    errorVerification: 'Verification failed. Try again.',
    errorLogin: 'Login failed. Check credentials and try again.',
    fillAllFields: 'Please fill in all fields.',
    codeResentSuccess: 'Verification code resent successfully.',
    errorOAuth: 'OAuth login failed.',
    googleDev: 'Google Account',
    githubDev: 'GitHub Account',

    // New Auth page-specific keys
    loginFieldsRequired: 'Please fill in all fields.',
    passwordsDoNotMatch: 'Passwords do not match.',
    signupFailed: 'Signup failed. Email might be in use.',
    backToLogin: 'Back to Login',
    createAccount: 'Create Account',
    haveAccount: 'Already have an account?',

    // Landing Page
    landingTitle1: 'Your codebase is',
    landingTitle2: 'your engineering brain.',
    landingSubtitle: 'Stop searching folders or browsing GitHub. DevVault AI indexes and explains your repositories so you can find code and get answers in plain natural language.',
    landingSearchTitle: 'Semantic Smart Search',
    landingSearchDesc: 'Find files, functions, and old bug solutions using natural language, like "where did I implement Stripe webhooks?" to get the exact location.',
    landingChatTitle: 'Context-Aware AI Chat',
    landingChatDesc: 'Ask your imported repositories directly, understand system architecture, and get code explanations with clear source references.',
    landingDnaTitle: 'Automated Developer DNA',
    landingDnaDesc: 'Upload ZIP archives and the system extracts classes, routes, schemas, frameworks, and visualizes dependencies in the background.',
    landingSnippetsTitle: 'Snippets & Errors Vault',
    landingSnippetsDesc: 'Store critical code pieces and bug fixes along with causes and before/after code blocks for future reuse.',
    landingShieldTitle: 'Secret Leak Prevention',
    landingShieldDesc: 'The system scans database credentials and API keys, redacting sensitive parameters before storage.',
    landingHealthTitle: 'Repository Health Scoring',
    landingHealthDesc: 'Analyze source files to detect dead code, empty catch blocks, and technical debt with a detailed actionable score.',
    landingPricingTitle: 'Simple, Transparent Plans',
    landingPricingSubtitle: 'Choose the tier that fits your codebase size and features.',
    landingPricingFreeName: 'Free Starter',
    landingPricingFreeDesc: 'For personal use and quick indexing',
    landingPricingProName: 'Pro Developer',
    landingPricingProDesc: 'Best for active developers and freelancers',
    landingPricingTeamName: 'Team Brain',
    landingPricingTeamDesc: 'For small engineering teams and shared space',
    landingPricingFreeCTA: 'Get Started',
    landingPricingProCTA: 'Upgrade to Pro',
    landingPricingTeamCTA: 'Start Team Trial',
    landingPopular: 'Popular',
    landingPricePeriodMonth: '/ month',
    landingPricePeriodFree: '/ forever',
    landingSearchPlaceholder: 'e.g. where did I implement Stripe webhooks?',
    landingStartFree: 'Start Free',
    landingExploreFeatures: 'Explore Features',
    landingHeaderTitle: 'DevVault AI',

    // Projects & Import
    errorProjectZip: 'Please specify a project name and select a ZIP archive.',
    preparingIndexing: 'Preparing indexing task...',
    errorUploadFailed: 'File upload failed.',
    confirmDeleteProject: 'Are you sure you want to delete this project? All index data, code blocks, and vector embeddings will be permanently removed.',
    deleteProjectBtn: 'Delete Project',
    downloadZip: 'Download ZIP',
    loadingProjects: 'Loading repositories...',
    yourRepositories: 'Your Repositories',
    manageReposDesc: 'Manage and import codebases for AI analysis.',
    importProject: 'Import Project',
    indexingCodebase: 'Indexing codebase...',
    importZipProject: 'Import ZIP Project',
    viewPlansAndUpgrade: 'View Plans & Upgrade',
    optionalDetails: 'Optional details',
    clickToChooseZip: 'Click to choose repository ZIP',
    supportedFormatZip: 'Supported format: ZIP archive up to 50MB',
    uploadingZip: 'Uploading ZIP...',
    startIndexing: 'Start Indexing',
    noDescription: 'No description provided.',
    health: 'Health',
    noProjectsImportedYet: 'No projects imported yet.',
    noProjectsImportedDesc: 'Click "Import Project" and upload a codebase ZIP.',
    loadingProjectMetrics: 'Loading project metrics...',
    healthScore: 'Health Score',
    overview: 'Overview',
    files: 'Files',
    chat: 'Chat',
    graph: 'Dependency Graph',
    replay: 'Project Replay',
    systemProperties: 'System Properties',
    language: 'Language',
    framework: 'Framework',
    database: 'Database',
    totalFiles: 'Total Files',
    indexedClassesRoutes: 'Indexed Classes/Routes',
    projectSize: 'Project Size',
    aiGeneratedDoc: 'AI Documentation',
    frameworkLanguageRecognized: 'This project has been recognized as a **{framework}** codebase using **{language}**.',
    containsFlows: 'It includes flows containing schemas, controllers, and services.',
    databaseLayer: 'Database Layer',
    databaseUsed: 'Uses **{database}** as data store. Schemas are linked to the prompt context.',
    securityAnalysis: 'Secrets & Security Analysis',
    noSecretsExposed: 'No active secrets or API credentials exposed. Any sensitive variables discovered were excluded from indexing.',
    workspaceFiles: 'Workspace Files',
    explainCode: 'Explain Code',
    copyCode: 'Copy Code',
    loadingFile: 'Loading file content...',
    chooseFileToPreview: 'Select a file from the tree to preview.',
    aiExplanations: 'AI Insights',
    analyzingFileLogic: 'Analyzing logic...',
    fileSummary: 'File Summary',
    deepCodeReview: 'Deep Code Review',
    clickExplainToAnalyze: 'Click "Explain Code" to run structured analysis.',
    askContextOnly: 'Ask questions strictly scoped to **{projectName}**.',
    askInProjectFiles: 'Ask in {projectName} files...',
    graphExplorer: 'Dependency Explorer',
    graphNodesDesc: 'Nodes represent indexed source files, edges indicate import dependencies.',
    nodesCount: '{count} Nodes',
    edgesCount: '{count} Edges',
    graphInteractInstruction: 'Pinch/Scroll to Zoom • Drag to Move',
    noRelationsExtracted: 'No dependencies detected. Index a project with valid imports.',
    replayTimeline: 'Project Replay Timeline',
    phase: 'Phase',
    relatedFiles: 'Related Files',
    noReplayEvents: 'No replay events logged for this project.',

    // Snippets Vault
    deleteSnippetConfirm: 'Delete this code snippet?',
    loadingSnippets: 'Loading snippets vault...',
    snippetsVault: 'Snippets Vault',
    snippetsVaultDesc: 'Reusable, organized, searchable code snippets.',
    addSnippet: 'Add Snippet',
    addNewSnippet: 'Add New Snippet',
    snippetTitle: 'Title',
    exampleSupabaseAuth: 'e.g. Supabase Auth Helper',
    snippetCode: 'Snippet Code',
    pasteReusableCode: 'Paste your reusable code block here',
    explanation: 'Explanation',
    shortExplanation: 'Short summary of what this code does',
    tagsCommaSeparated: 'Tags, comma-separated',
    savingSnippet: 'Saving...',
    saveSnippet: 'Save Snippet',
    filterSnippets: 'Filter by tag or language...',
    noExplanation: 'No explanation provided.',
    noSnippetsText: 'No snippets found. Add your first reusable code snippet!',
    aiExplanation: 'AI Explanation',
    noSummary: 'No summary.',
    codePreview: 'Code Preview',
    copied: 'Copied',
    chooseSnippetToPreview: 'Select a snippet to review explanations and preview code.',

    // Errors Library
    deleteErrorConfirm: 'Delete this logged error?',
    loadingErrors: 'Loading errors library...',
    errorsLibrary: 'Errors Library',
    errorsLibraryDesc: 'Database of technical bugs, causes, and solved solutions.',
    logError: 'Log Error',
    logSolvedError: 'Log Solved Error',
    errorTitlePlaceholder: 'e.g. Supabase Storage upload file limit',
    relatedProject: 'Related Project',
    genericNoProject: 'Generic (No Project)',
    errorMessageLog: 'Error Message / Log Trace',
    pasteErrorTrace: 'Paste error stack trace or console output',
    errorCause: 'Root Cause',
    whyErrorHappened: 'Why did this error happen?',
    errorSolution: 'Resolution',
    howErrorSolved: 'How did you solve this issue?',
    codeBeforeFix: 'Code Before Fix',
    codeBeforeFixPlaceholder: 'Error-prone code block',
    codeAfterFix: 'Code After Fix',
    codeAfterFixPlaceholder: 'Fixed code block',
    saveLog: 'Save Log',
    searchErrorsPlaceholder: 'Search by title, tag, or error trace...',
    noErrorsText: 'No errors logged yet. Capture bug-solution cases here.',
    solution: 'Solution',
    codeFixComparison: 'Before/After Code Comparison',
    chooseErrorToPreview: 'Select an error entry to inspect root cause, resolution, and code.',

    // Reusable Systems Blueprints
    deleteSystemConfirm: 'Delete this reusable system blueprint?',
    loadingSystems: 'Loading reusable systems...',
    systemsTitle: 'Reusable Systems',
    systemsSubtitle: 'Scaffolded design templates and architectures.',
    addSystem: 'Add System',
    defineSystemTemplate: 'Define Reusable System Blueprint',
    systemName: 'System Name',
    exampleSystemName: 'e.g. Firebase Auth with RBAC',
    systemType: 'Type',
    typeAuth: 'Authentication',
    typePayments: 'Payments & Billing',
    typeFileUpload: 'File Upload & Storage',
    typeDatabase: 'Database Schema',
    typeNotification: 'Notifications',
    systemDescription: 'Description',
    describeSystemFunc: 'Describe how this system operates',
    relatedFilesComma: 'Related files (comma-separated)',
    setupStepsComma: 'Setup steps (comma-separated)',
    dependenciesComma: 'Dependencies (comma-separated)',
    flowchartSetupCode: 'Flow diagram / Bootstrap code',
    setupInstructionsPlaceholder: 'Setup commands or template configs',
    savingSystemTemplate: 'Saving blueprint...',
    saveSystemTemplate: 'Save Blueprint',
    dependenciesCount: '{count} Dependencies',
    noSystemsText: 'No systems defined. Create components to bootstrap.',
    requiredDependencies: 'Required Dependencies',
    setupInstructions: 'Setup Instructions',
    systemFlowchart: 'System Flowchart / Config',
    generateInstance: 'Generate Instance',
    chooseSystemToPreview: 'Select a system blueprint to view configuration and files.',

    // Developer DNA
    loadingDna: 'Loading Developer DNA profile...',
    dnaTitle: 'Developer DNA',
    dnaSubtitle: 'Engineering profile and code metrics generated by AI.',
    updateDna: 'Update DNA',
    favoriteTechs: 'Preferred Tech Stack',
    dnaLanguage: 'Language',
    dnaFramework: 'Framework',
    dnaDatabase: 'Database',
    engineeringStrengths: 'Engineering Strengths',
    backendSystems: 'Backend Systems',
    frontendInterfaces: 'Frontend Interfaces',
    mobileApps: 'Mobile Applications',
    devopsCloud: 'DevOps & Cloud Setup',
    codeStyleScanner: 'Code Style Scanner',
    pasteToCompareStyle: 'Paste a code block to compare naming conventions, spacing, and error-handling styles against your profile style ({style}).',
    pasteCodeHere: 'Paste code block here...',
    analyzingStyle: 'Analyzing style...',
    checkStyleMatch: 'Check Style Match',
    styleSimilarity: 'Style Similarity',
    pasteCodeToCompare: 'Paste code on the left to check consistency with your profile.',
    errorLoadingDna: 'Failed to load Developer DNA. Index projects first to build your profile.',
    productivityScore: 'Productivity Score',
    productivityDescription: 'Your output is in the top 2% of elite contributors this sprint.',
    techBreakdown: 'Technology Breakdown',
    techBreakdownSubtitle: 'Ecosystem distribution by compute time',
    cloudNative: 'Cloud Native',
    webEngine: 'Web Engine',
    machineLearning: 'Machine Learning',
    legacySupport: 'Legacy Support',
    topLanguages: 'Top Languages',
    skillGrowthCurve: 'Skill Growth Curve',
    expertiseVelocity: 'Aggregated expertise velocity (Last 6 Months)',
    preferredPattern: 'Preferred Pattern',
    stylisticIdentity: 'Stylistic Identity',
    dnaAnalytics: 'DNA Analytics',
    dnaPerformance: 'Performance',
    dnaSecurity: 'Security',
    searchInsights: 'Search insights...',
    deployDna: 'Deploy DNA',

    // Time Machine
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    September: 'September',
    October: 'October',
    November: 'November',
    December: 'December',
    januaryShort: 'Jan',
    februaryShort: 'Feb',
    marchShort: 'Mar',
    aprilShort: 'Apr',
    mayShort: 'May',
    juneShort: 'Jun',
    julyShort: 'Jul',
    augustShort: 'Aug',
    septemberShort: 'Sep',
    octoberShort: 'Oct',
    novemberShort: 'Nov',
    decemberShort: 'Dec',
    loadingTimeMachine: 'Loading Time Machine...',
    timeMachineTitle: 'Time Machine',
    timeMachineSubtitle: 'Step back in time to review old files, resolved bugs, and workflows.',
    choosePeriod: 'Select range:',
    askPastMemory: 'Query Past Developer Memory',
    askPastMemoryPlaceholder: 'e.g. How did I fix Authentication or file upload issues during this period?',
    askAi: 'Query AI',
    timelineActivityLog: 'Historical Activity Log',
    noActivitiesPeriod: 'No activity found in this period. Select another date range.',

    // Team Workspace
    teamWorkspace: 'Team Workspace',
    addingMember: 'Adding member...',
    addMemberSuccess: 'Member added successfully.',
    addMemberFailed: 'Invitation failed. Verify the email is registered on DevVault.',
    loadingTeamBrain: 'Loading Team Brain workspace...',
    teamBrainTitle: 'Team Brain',
    teamBrainSubtitle: 'Shared engineering context and files for software teams.',
    inviteMember: 'Add Member',
    inviteDeveloper: 'Invite Developer to Workspace',
    userEmail: 'User Email',
    memberRole: 'Member Role',
    roleMemberDesc: 'Member (Read & Write)',
    roleAdminDesc: 'Admin (Full Management)',
    addTeamMember: 'Add Team Member',
    activeMembers: 'Active Members ({count})',
    removeMember: 'Remove Member',
    noActiveMembers: 'No active team members.',
    workspacePermissions: 'Workspace Permissions',
    rbacNotice: 'Team permissions are governed via RBAC. Admins can upload and purge codebase indexes, while members can search and query.',
    knowledgeLock: 'Knowledge Lock: When a engineer leaves the organization, indexed insights, snippets, and bug resolution logs remain stored securely inside the company vault.',

    // Billing & Plans
    stripeInitFailed: 'Failed to initialize Stripe checkout.',
    stripeNotConfigured: 'Stripe not configured. Emulating developer local upgrade.',
    upgradePlanSuccess: 'Upgraded to {plan} subscription plan.',
    upgradePlanFailed: 'Upgrade failed. Please try again.',
    loadingBillingData: 'Loading subscription data...',
    pricingFreeStarter: 'Free Starter',
    pricingFreeStarterDesc: 'Test codebase indexing and semantic search',
    pricingFreeStarterPeriod: 'forever',
    pricingCurrentPlan: 'Current Plan',
    quotaActiveRepos: 'Up to 2 active repositories',
    quotaCloudStorageFree: '100MB secure storage',
    quotaRagFree: '20 AI RAG questions per month',
    quotaSecretScan: 'Secrets scanning & leak prevention',
    quotaLocalSearch: 'Keyword and semantic code search',
    pricingProName: 'Pro Developer',
    pricingProDesc: 'The most popular plan for active engineers',
    pricingProPeriod: 'month',
    pricingProCTA: 'Upgrade to Pro',
    quotaActiveReposPro: 'Up to 15 active repositories',
    quotaCloudStoragePro: '2GB cloud storage',
    quotaRagPro: '250 AI RAG questions per month',
    quotaDependencyGraph: 'Interactive dependency graphs',
    quotaProjectReplay: 'Interactive project code replays',
    quotaStyleMatch: 'Developer style fingerprints match',
    pricingTeamName: 'Team Brain',
    pricingTeamDesc: 'Shared engineering context for small teams',
    pricingTeamPeriod: 'month',
    pricingTeamCTA: 'Upgrade to Team',
    quotaActiveReposTeam: 'Up to 100 active repositories',
    quotaCloudStorageTeam: '20GB team cloud storage',
    quotaRagTeam: '1,500 AI RAG questions per month',
    quotaTeamInvites: 'Team invites & seats management',
    quotaSharedCatalog: 'Shared snippets and bugs catalogs',
    quotaRbac: 'RBAC permissions control',
    billingAndPlans: 'Subscription & Billing',
    billingMonitorDesc: 'Monitor usage logs, plan limits, and manage your billing.',
    planLabel: 'Current Plan: {plan}',
    activeReposLabel: 'Active Repositories',
    reposIndexedDesc: 'Active repositories indexed in context',
    indexedCodeStorage: 'Indexed Code Storage',
    fileSizeExtractedDesc: 'Total codebase contents size extracted from ZIPs',
    monthlyQueriesLabel: 'Monthly AI Queries',
    queriesRagDesc: 'Questions asked to RAG assistant or code summaries this month',
    choosePlan: 'Select Your Tier',
    activePlan: 'Active Plan',
    whatYouGet: 'What you will get',

    // OAuth Callback
    oauthNoPayload: 'OAuth payload not found.',
    oauthLoginFailed: 'OAuth login failed',
    oauthCompleting: 'Completing login...',
    oauthSavingSession: 'Saving DevVault AI session securely.',

    // Spotlight / Command Palette
    explainCodePart: 'Explain this part of the code: {name}',
    all: 'All',
    file: 'Files',
    codeEntity: 'Code',
    snippet: 'Snippets',
    errorSolutionFilter: 'Errors',
    searchPalettePlaceholder: 'Search files, functions, errors, and snippets...',
    searchPaletteGuide: 'Search inside indexed files, code entities, snippets, and error solutions.',
    matchScore: 'Match {score}%',
    open: 'Open',
    noMatchResults: 'No matching results in your developer memory.',
    smartSearchReady: 'Smart engineering search ready.',
    smartSearchInstruction: 'Type to search code snippets, file descriptions, logged errors, or saved snippets.',

    // Chat Page
    reachedRagLimit: 'You have reached the monthly AI queries limit. Please upgrade your subscription to continue.',
    chatErrorOccurred: 'Failed to process chat query. Check connection and try again.',
    loadingChatSpace: 'Loading AI chat workspace...',
    newChat: 'New Chat',
    projectScope: 'Project Scope',
    searchAllRepos: 'Search all repositories',
    loadedSources: 'Loaded Sources',
    openSourceDetails: 'Open {path} from project details to review the full source.',
    chooseProjectToLoadFiles: 'Choose a project to load files into the AI context.',
    recentChats: 'Recent Chats',
    noRecentChats: 'No recent chats.',
    upgradeSubscription: 'Upgrade Subscription',
    aiAssistant: 'DevVault AI Assistant',
    askAnythingRepo: 'Ask anything about your uploaded projects and past coding knowledge.',
    askAiAboutRepos: 'Ask DevVault AI about your software projects...',
    codeWorkspace: 'AI Code Space',
    contextAwareCodePreview: 'Context-Aware Code Preview',
    askQuestionToPreview: 'Ask a question or open a referenced source. DevVault will display the code, summaries, and optimization notes here.',
    codeExplanation: 'Code Explanation',
    dependencies: 'Dependencies',
    optimizations: 'Optimizations',
    securityAnalysisLabel: 'Security Analysis',
    loadedSourcesCount: 'Loaded Sources: {count}',
    // Notifications System
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    noNotifications: 'No new notifications',
    deleteNotification: 'Delete notification',
    clearAll: 'Clear all',
    notificationSuccess: 'Success',
    notificationInfo: 'Info',
    notificationWarning: 'Warning',
    notificationError: 'Error'
  },
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    projects: 'المشاريع',
    aiChat: 'محادثة الذكاء',
    snippets: 'مكتبة المقاطع',
    errors: 'مكتبة الأخطاء',
    systems: 'الأنظمة القابلة لإعادة الاستخدام',
    developerDna: 'بصمة المطور',
    timeMachine: 'آلة الزمن',
    team: 'عقل الفريق',
    billing: 'الفوترة والخطط',
    adminPanel: 'لوحة الإدارة',
    profileSettings: 'الملف الشخصي والإعدادات',
    logout: 'تسجيل الخروج',
    newProject: 'مشروع جديد',
    cloudStorage: 'التخزين السحابي',
    searchMemory: 'ابحث في الذاكرة...',
    intelligentDeveloperMemory: 'منصة المطور الذكية',
    switchLanguageTitle: 'التحويل إلى الإنجليزية',

    // General UI
    free: 'مجاني',
    pro: 'برو',
    teamPlan: 'فريق',
    upgradeBtn: 'ترقية الآن',
    cancel: 'إلغاء',
    save: 'حفظ',
    loading: 'جاري التحميل...',
    settings: 'الإعدادات',
    saveSuccess: 'تم حفظ الإعدادات بنجاح!',
    errorOccurred: 'حدث خطأ ما.',
    
    // Dashboard & Spotlight
    welcomeBack: 'مرحباً بك مجدداً',
    aiDailyStandup: 'مولد التقرير اليومي بالذكاء الاصطناعي',
    generateStandup: 'توليد التقرير اليومي',
    hiddenKnowledge: 'مكتشف المعرفة المخفية (التكرار)',
    opportunityEngine: 'محرك الفرص SaaS',
    activeAlerts: 'التنبيهات النشطة',
    recentProjects: 'المشاريع الأخيرة',
    generic: 'عام',
    vanilla: 'فانيلا',
    indexedFiles: 'ملفات مفهرسة',
    smartSnippets: 'مقاطع ذكية',
    solvedErrors: 'أخطاء محلولة',
    reusableSystems: 'الأنظمة',
    aiQueries: 'أسئلة الذكاء',
    navDashboard: 'الصفحات / لوحة التحكم',
    systemOverview: 'نظرة عامة على النظام',
    searchPlaceholder: 'ابحث في المعمارية والمقاطع...',
    welcomeUser: 'أهلاً',
    dashboardSubtitle: 'هذا ملخص ذاكرتك البرمجية المتزامنة',
    developerDnaHealth: 'صحة بصمة المطور',
    indexedFromRepos: '↗ مفهرسة من المستودعات النشطة',
    highEngineeringMemory: 'ذاكرة هندسية عالية',
    activeProjects: 'المشاريع النشطة',
    searchEngineering: 'ابحث في عقلك الهندسي...',
    searchInstruction: 'اضغط ⌘K للبحث في الكود، المشاريع أو الحلول.',
    projectHealth: 'صحة المشاريع',
    repoStatus: 'حالة مستودعاتك داخل الخزنة بشكل مباشر',
    viewAll: 'عرض الكل',
    dailyDeveloperReport: 'التقرير اليومي للمطور',
    dailyReportDesc: 'توليد تقرير يومي ذكي بالاعتماد على نشاطاتك الأخيرة.',
    generateReport: 'توليد التقرير',
    generatingReport: 'جاري توليد التقرير...',
    hiddenKnowledgeFinder: 'مكتشف المعرفة المخفية',
    hiddenKnowledgeDesc: 'اكتشاف وتجنب التكرار البرمجي بين مشاريعك.',
    scanDuplicates: 'البحث عن تكرار الكود',
    smartOpportunityEngine: 'محرك الفرص الذكي',
    opportunityDesc: 'تحليل كودك واقتراح أفكار مشاريع تجارية متكاملة (SaaS).',
    generateSaaS: 'توليد فكرة SaaS',
    recentActivityLog: 'سجل النشاطات الأخيرة',
    recentActivityDesc: 'تتبع التغييرات والعمليات التي تمت في حسابك',

    // New Dashboard specific translations
    dashboardWelcomeBack: 'مرحباً بعودتك',
    dashboardWelcomeUser: 'أهلاً، {name}',
    dashboardHealthDna: 'صحة بصمة المطور',
    dashboardActiveProjects: 'المشاريع النشطة',
    dashboardAiInsights: 'استنتاجات الذكاء',
    dashboardSearchPlaceholder: 'ابحث في عقلك الهندسي...',
    dashboardSearchCommand: 'اضغط ⌘K للبحث في الكود، المشاريع أو الحلول.',
    dashboardStatsProjects: 'المشاريع',
    dashboardStatsFiles: 'ملفات مفهرسة',
    dashboardStatsSnippets: 'مقاطع ذكية',
    dashboardStatsErrors: 'أخطاء محلولة',
    dashboardStatsSystems: 'أنظمة',
    dashboardStatsQueries: 'أسئلة الذكاء',
    dashboardProjectHealth: 'صحة المشاريع',
    dashboardRepoStatus: 'حالة مستودعاتك داخل الخزنة بشكل مباشر',
    dashboardViewAll: 'عرض الكل',
    dashboardNoProjects: 'لا توجد مشاريع مرفوعة بعد. ارفع ملفات ZIP لبدء الفهرسة.',
    dashboardSmartSuggestion: 'اقتراح ذكي: تم اكتشاف نظام قابل لإعادة الاستخدام',
    dashboardJWTNotice: 'لاحظنا أنك أنشأت بنية JWT متشابهة في عدة ملفات. يمكنك تحويلها إلى نظام قابل لإعادة الاستخدام لتكرارها بسرعة في الخدمات القادمة.',
    dashboardGenerateSystem: 'توليد نظام قابل لإعادة الاستخدام',
    dashboardActivityTitle: 'نشاط الذكاء',
    dashboardNoActivity: 'لا توجد أنشطة حديثة. ارفع مستودعاً لبدء التتبع.',
    dashboardOpenChat: 'افتح محادثة الذكاء',
    dashboardDailyReport: 'تقرير يومي ذكي',
    dashboardDailyReportDesc: 'أنشئ تقرير حالة يومي يلخص الرفعات الأخيرة، المقاطع الجديدة، والأخطاء التي تم حلها.',
    dashboardCopyReport: 'نسخ التقرير',
    dashboardReportCopied: 'تم نسخ التقرير.',
    dashboardDailyStandup: 'تقرير يومي ذكي',
    dashboardGenerateReport: 'توليد التقرير',
    dashboardGeneratingReport: 'جاري التوليد...',
    dashboardHiddenKnowledge: 'اكتشاف المعرفة المخفية',
    dashboardHiddenKnowledgeDesc: 'يفحص الذكاء تاريخ الكود لاكتشاف الأنماط والبنى المتكررة التي قد تكون نسيتها.',
    dashboardNoRepeats: 'لم يتم اكتشاف أنماط متكررة بعد. ارفع مستودعات أكثر للمقارنة.',
    dashboardOpportunityTitle: 'محرك الفرص',
    dashboardOpportunityDesc: 'يحلل الذكاء نقاط قوة تقنياتك وعدد مشاريعك ليقترح قوالب SaaS قابلة للبيع.',
    dashboardExportBlueprint: 'تصدير قالب جاهز',
    activitySystemLog: 'سجل النظام',
    activityUploadProject: 'رفع مشروع',
    activitySnippetsLib: 'مكتبة المقاطع',
    activityErrorsLib: 'مكتبة الأخطاء',
    activityReusableSys: 'نظام قابل لإعادة الاستخدام',
    activityTimeNow: 'الآن',
    activityTimeDays: 'منذ {count} يوم',
    activityTimeHours: 'منذ {count} ساعة',
    activityTimeMins: 'منذ {count} دقيقة',
    activityUploadedRepo: 'تم رفع مستودع: {name}',
    
    // Profile & Settings
    profileTitle: 'الملف الشخصي والإعدادات',
    profileSubtitle: 'أضف طابعك الشخصي وتحكم في تفاصيل حسابك وإعدادات الإشعارات والألوان.',
    personalInfo: 'المعلومات الشخصية',
    security: 'الأمان والحماية',
    preferences: 'تفضيلات التطبيق',
    nameLabel: 'الاسم الكامل',
    emailLabel: 'البريد الإلكتروني',
    bioLabel: 'نبذة تعريفية / المسمى الوظيفي',
    avatarLabel: 'رابط الصورة الرمزية',
    avatarPresets: 'اختر رمزاً جاهزاً',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    accentColor: 'لون السمة المميز',
    accentBlue: 'أزرق كلاسيكي',
    accentPurple: 'بنفسجي ملكي',
    accentAmber: 'ذهبي دافئ',
    accentGreen: 'أخضر زمردي',
    notificationsTitle: 'تفضيلات الإشعارات',
    emailNotifications: 'إشعارات البريد الإلكتروني الأسبوعية',
    aiInsights: 'تحليلات الذكاء الاصطناعي الأسبوعية للكود',
    securityAlerts: 'تنبيهات الأمان وتجاوز حدود الخطة',
    saveSettings: 'حفظ جميع الإعدادات',
    updating: 'جاري التحديث...',
    joinedDate: 'تاريخ الانضمام',
    currentPlan: 'الخطة الحالية',
    storageUsed: 'المساحة المستخدمة',
    limitExceededMsg: 'لقد تجاوزت الحد المسموح به لخطة حسابك. يرجى الترقية للاستمرار.',
    loadingProfileSettings: 'جاري تحميل إعدادات الحساب...',
    passwordUpdatedSuccess: 'تم تحديث كلمة المرور بنجاح!',
    bioPlaceholder: 'مثال: مهندس برمجيات أول | مهتم بالذكاء الاصطناعي وهندسة النظم',
    passwordSecurityNote: 'قم بتغيير كلمة المرور الخاصة بك بشكل دوري لحماية حسابك.',
    preferencesSubtitle: 'خصص واجهة المستخدم الخاصة بك وتفضيلات التنبيهات.',
    weeklyEmailDesc: 'احصل على ملخص هندسي أسبوعي بالبريد الإلكتروني.',
    aiInsightsDesc: 'مزامنة اقتراحات الذكاء لتحديث معمارية كودك.',
    securityAlertsDesc: 'تنبيهات عند تسرب أسرار أو تجاوز الحصص في المشاريع.',
    billingQuotaDesc: 'متابعة حدود واستهلاك الخطة الحالية.',
    needMoreResources: 'هل تحتاج إلى المزيد من الموارد؟',
    upgradeForHigherLimits: 'قم بالترقية إلى خطة Pro أو Team للحصول على حدود أعلى.',

    // Auth & Verify
    loginTitle: 'تسجيل الدخول',
    enterMemory: 'ادخل إلى ذاكرتك البرمجية',
    emailPlaceholder: 'البريد الإلكتروني',
    passwordPlaceholder: 'كلمة المرور',
    loginBtn: 'تسجيل الدخول',
    orContinueWith: 'أو الاستمرار باستخدام',
    dontHaveAccount: 'ليس لديك حساب؟',
    registerNow: 'سجل الآن',
    confirmEmail: 'تأكيد البريد الإلكتروني',
    codeSentMsg: 'أرسلنا كود تحقق من 6 أرقام إلى',
    enterCodePlaceholder: 'اكتب كود التحقق',
    devCodeLabel: 'كود التجربة',
    confirmAndLoginBtn: 'تأكيد وتسجيل الدخول',
    resendCodeBtn: 'إعادة إرسال الكود',
    resendingCode: 'جاري الإرسال...',
    backToLoginBtn: 'رجوع لتسجيل الدخول',
    errorVerification: 'فشل التحقق. حاول مرة أخرى.',
    errorLogin: 'فشل تسجيل الدخول. تحقق من بياناتك وحاول مرة أخرى.',
    fillAllFields: 'من فضلك املأ كل الحقول.',
    codeResentSuccess: 'تم إرسال كود التحقق مرة أخرى.',
    errorOAuth: 'فشل تسجيل الدخول عبر OAuth.',
    googleDev: 'مطور Google',
    githubDev: 'مهندس GitHub',

    // New Auth page-specific keys
    loginFieldsRequired: 'من فضلك املأ كل الحقول.',
    passwordsDoNotMatch: 'كلمتا المرور غير متطابقتين.',
    signupFailed: 'فشل إنشاء الحساب. قد يكون البريد مستخدماً بالفعل.',
    backToLogin: 'العودة لتسجيل الدخول',
    createAccount: 'إنشاء حساب جديد',
    haveAccount: 'لديك حساب بالفعل؟',

    // Landing Page
    landingTitle1: 'قاعدة الكود الخاصة بك هي',
    landingTitle2: 'عقلك الهندسي.',
    landingSubtitle: 'توقف عن البحث اليدوي داخل المجلدات القديمة ومستودعات GitHub. يقوم DevVault AI بفهرسة مشاريعك وتلخيصها حتى تصل للكود وتسأل عنه باللغة الطبيعية.',
    landingSearchTitle: 'بحث دلالي ذكي',
    landingSearchDesc: 'اعثر على الملفات والدوال وحلول الأخطاء القديمة باللغة الطبيعية، مثل: "أين نفذت Stripe webhooks؟" لتحصل على الملفات الدقيقة.',
    landingChatTitle: 'محادثة ذكية مع الكود',
    landingChatDesc: 'اسأل مستودعاتك المستوردة مباشرة، افهم المعمارية، واحصل على شرح للكود مع مصادر واضحة.',
    landingDnaTitle: 'استخراج بصمة الكود تلقائياً',
    landingDnaDesc: 'ارفع ملفات ZIP وسيستخرج النظام الكلاسات، المسارات، النماذج، بنية الفريمورك، ورسم الاعتماديات في الخلفية.',
    landingSnippetsTitle: 'خزنة المقاطع والأخطاء',
    landingSnippetsDesc: 'احفظ حلول الأخطاء والمقاطع المهمة مع السبب والكود قبل وبعد الإصلاح لتستخدمها لاحقاً.',
    landingShieldTitle: 'منع تسريب الأسرار',
    landingShieldDesc: 'يفحص النظام المفاتيح السرية وبيانات قواعد البيانات وخدمات الطرف الثالث ويخفيها قبل التخزين.',
    landingHealthTitle: 'مؤشرات صحة الكود',
    landingHealthDesc: 'حلل الملفات لاكتشاف الكود الميت، كتل catch الفارغة، والدين التقني مع درجة صحة وخطوات تحسين.',
    landingPricingTitle: 'خطط بسيطة ومناسبة',
    landingPricingSubtitle: 'اختر الخطة المناسبة لحجم أعمالك ومشاريعك',
    landingPricingFreeName: 'الخطة المجانية',
    landingPricingFreeDesc: 'للاستخدام الشخصي للمطورين',
    landingPricingProName: 'المطور المحترف',
    landingPricingProDesc: 'مناسبة للمستقلين والمطورين المحترفين',
    landingPricingTeamName: 'عقل الفريق',
    landingPricingTeamDesc: 'لفرق التطوير الصغيرة ومساحات العمل',
    landingPricingFreeCTA: 'ابدأ الآن',
    landingPricingProCTA: 'اشترك Pro',
    landingPricingTeamCTA: 'ابدأ تجربة الفريق',
    landingPopular: 'الأكثر شعبية',
    landingPricePeriodMonth: '/ شهرياً',
    landingPricePeriodFree: '/ دائماً',
    landingSearchPlaceholder: 'مثال: أين نفذت Stripe webhooks؟',
    landingStartFree: 'ابدأ مجاناً',
    landingExploreFeatures: 'مراجعة الميزات',
    landingHeaderTitle: 'ذاكرة هندسية ذكية',

    // Projects & Import
    errorProjectZip: 'من فضلك أدخل اسم المشروع واختر ملف ZIP.',
    preparingIndexing: 'جاري تجهيز طلب الفهرسة...',
    errorUploadFailed: 'فشل رفع الملف.',
    confirmDeleteProject: 'هل أنت متأكد من حذف هذا المشروع؟ سيتم حذف كل الفهارس وعناصر الكود والمتجهات المرتبطة به نهائياً.',
    deleteProjectBtn: 'حذف المشروع',
    downloadZip: 'تنزيل الملفات مضغوطة',
    loadingProjects: 'جاري تحميل المستودعات...',
    yourRepositories: 'مستودعاتك',
    manageReposDesc: 'أدر وارفع مكتبات الكود لتحليلها بالذكاء الاصطناعي',
    importProject: 'استيراد مشروع',
    indexingCodebase: 'جاري فهرسة قاعدة الكود...',
    importZipProject: 'استيراد مشروع ZIP',
    viewPlansAndUpgrade: 'عرض الخطط والترقية',
    optionalDetails: 'تفاصيل اختيارية',
    clickToChooseZip: 'اضغط لاختيار ملف ZIP للمشروع',
    supportedFormatZip: 'الصيغة المدعومة: أرشيف ZIP حتى 50MB',
    uploadingZip: 'جاري رفع ZIP...',
    startIndexing: 'بدء الفهرسة',
    noDescription: 'لا يوجد وصف.',
    health: 'الصحة',
    noProjectsImportedYet: 'لم يتم استيراد أي مشاريع بعد',
    noProjectsImportedDesc: 'اضغط "استيراد مشروع" وارفع ملف ZIP لقاعدة الكود.',
    loadingProjectMetrics: 'جاري تحميل مؤشرات المشروع...',
    healthScore: 'درجة الصحة',
    overview: 'نظرة عامة',
    files: 'الملفات',
    chat: 'المحادثة',
    graph: 'الرسم',
    replay: 'الخط الزمني',
    systemProperties: 'خصائص النظام',
    language: 'اللغة',
    framework: 'الفريمورك',
    database: 'قاعدة البيانات',
    totalFiles: 'إجمالي الملفات',
    indexedClassesRoutes: 'كلاسات/مسارات مفهرسة',
    projectSize: 'حجم المشروع',
    aiGeneratedDoc: 'توثيق مولد بالذكاء',
    frameworkLanguageRecognized: 'تم التعرف على هذا المشروع كقاعدة كود **{framework}** تستخدم **{language}**.',
    containsFlows: 'يحتوي على تدفقات تشمل النماذج، المتحكمات، والخدمات.',
    databaseLayer: 'طبقة قاعدة البيانات',
    databaseUsed: 'يستخدم **{database}** كمخزن بيانات. تم تحليل وربط المخططات بذاكرة البرومبت.',
    securityAnalysis: 'تحليل الأمان والأسرار',
    noSecretsExposed: 'لا توجد أسرار نشطة مكشوفة في الملفات. المتغيرات الحساسة التي تم اكتشافها أثناء المعالجة تم استبعادها من الفهرسة.',
    workspaceFiles: 'ملفات مساحة العمل',
    explainCode: 'شرح الكود',
    copyCode: 'نسخ الكود',
    loadingFile: 'جاري تحميل الملف...',
    chooseFileToPreview: 'اختر ملفاً من الشجرة لمعاينة الكود.',
    aiExplanations: 'شروحات الذكاء',
    analyzingFileLogic: 'جاري تحليل منطق الملف...',
    fileSummary: 'ملخص الملف',
    deepCodeReview: 'فحص عميق للكود',
    clickExplainToAnalyze: 'اضغط "شرح الكود" لتشغيل فحص ذكي منظم.',
    askContextOnly: 'اسأل أسئلة ضمن سياق ملفات **{projectName}** فقط.',
    askInProjectFiles: 'اسأل داخل ملفات {projectName}...',
    graphExplorer: 'مستكشف الرسم',
    graphNodesDesc: 'العقد تمثل الملفات المفهرسة، والحواف توضح مسارات الاعتماديات.',
    nodesCount: '{count} عقد',
    edgesCount: '{count} روابط',
    graphInteractInstruction: 'مرر للتكبير • اسحب للتحريك',
    noRelationsExtracted: 'لم يتم استخراج علاقات. افهرس ملفات تحتوي على import dependencies.',
    replayTimeline: 'خط زمني لإعادة تشغيل المشروع',
    phase: 'مرحلة',
    relatedFiles: 'الملفات المرتبطة',
    noReplayEvents: 'لا توجد أحداث مسجلة لإعادة التشغيل.',

    // Snippets Vault
    deleteSnippetConfirm: 'هل تريد حذف هذا المقطع؟',
    loadingSnippets: 'جاري تحميل خزنة المقاطع...',
    snippetsVault: 'خزنة المقاطع',
    snippetsVaultDesc: 'وحدات كود قابلة لإعادة الاستخدام ومنظمة وقابلة للبحث',
    addSnippet: 'إضافة مقطع',
    addNewSnippet: 'إضافة مقطع جديد',
    snippetTitle: 'العنوان',
    exampleSupabaseAuth: 'مثال: مساعد Supabase Auth',
    snippetCode: 'مقطع الكود',
    pasteReusableCode: 'الصق مقطع الكود القابل لإعادة الاستخدام هنا',
    explanation: 'الشرح',
    shortExplanation: 'وصف مختصر لما يفعله الكود',
    tagsCommaSeparated: 'الوسوم، مفصولة بفواصل',
    savingSnippet: 'جاري الحفظ...',
    saveSnippet: 'حفظ المقطع',
    filterSnippets: 'فلترة المقاطع بالوسم أو اللغة...',
    noExplanation: 'لا يوجد شرح.',
    noSnippetsText: 'لا توجد مقاطع كود. أضف أول كود قابل لإعادة الاستخدام.',
    aiExplanation: 'شرح الذكاء',
    noSummary: 'لا يوجد ملخص.',
    codePreview: 'معاينة الكود',
    copied: 'تم النسخ',
    chooseSnippetToPreview: 'اختر مقطعاً لعرض الشرح وتفاصيل الكود.',

    // Errors Library
    deleteErrorConfirm: 'هل تريد حذف سجل الخطأ هذا؟',
    loadingErrors: 'جاري تحميل مكتبة الأخطاء...',
    errorsLibrary: 'مكتبة الأخطاء',
    errorsLibraryDesc: 'سجل للأخطاء التقنية وأسبابها وحلولها',
    logError: 'تسجيل خطأ',
    logSolvedError: 'تسجيل خطأ تم حله',
    errorTitlePlaceholder: 'مثال: خطأ رفع ملف في Supabase Storage',
    relatedProject: 'المشروع المرتبط',
    genericNoProject: 'عام، بدون مشروع',
    errorMessageLog: 'رسالة الخطأ / السجل',
    pasteErrorTrace: 'الصق رسالة الخطأ أو stack trace هنا',
    errorCause: 'سبب المشكلة',
    whyErrorHappened: 'لماذا حدث هذا الخطأ؟',
    errorSolution: 'طريقة الحل',
    howErrorSolved: 'كيف تم حل المشكلة؟',
    codeBeforeFix: 'الكود قبل الإصلاح',
    codeBeforeFixPlaceholder: 'الكود الذي سبب الخطأ',
    codeAfterFix: 'الكود بعد الإصلاح',
    codeAfterFixPlaceholder: 'الكود المصحح',
    saveLog: 'حفظ السجل',
    searchErrorsPlaceholder: 'ابحث في الأخطاء بالعنوان أو الوسم...',
    noErrorsText: 'لا توجد أخطاء مسجلة. احفظ ملاحظات أخطائك وحلولها هنا.',
    solution: 'الحل',
    codeFixComparison: 'مقارنة إصلاح الكود',
    chooseErrorToPreview: 'اختر خطأ لعرض التفاصيل والسبب والحل والكود قبل/بعد.',

    // Reusable Systems Blueprints
    deleteSystemConfirm: 'هل تريد حذف قالب النظام القابل لإعادة الاستخدام؟',
    loadingSystems: 'جاري تحميل الأنظمة القابلة لإعادة الاستخدام...',
    systemsTitle: 'الأنظمة القابلة لإعادة الاستخدام',
    systemsSubtitle: 'قوالب ومعماريات جاهزة قابلة للتكرار',
    addSystem: 'إضافة نظام',
    defineSystemTemplate: 'تعريف قالب نظام قابل لإعادة الاستخدام',
    systemName: 'اسم النظام',
    exampleSystemName: 'مثال: Firebase Auth وصلاحيات RBAC',
    systemType: 'النوع',
    typeAuth: 'مصادقة',
    typePayments: 'مدفوعات وفوترة',
    typeFileUpload: 'رفع ملفات وتخزين S3/Supabase',
    typeDatabase: 'مخطط قاعدة بيانات',
    typeNotification: 'إرسال إشعارات',
    systemDescription: 'الوصف',
    describeSystemFunc: 'صف طريقة عمل النظام',
    relatedFilesComma: 'الملفات المرتبطة، مفصولة بفواصل',
    setupStepsComma: 'خطوات الإعداد، مفصولة بفواصل',
    dependenciesComma: 'الاعتماديات، مفصولة بفواصل',
    flowchartSetupCode: 'مخطط التدفق / مقطع إعداد',
    setupInstructionsPlaceholder: 'إعدادات الكود أو تعليمات القالب',
    savingSystemTemplate: 'جاري حفظ القالب...',
    saveSystemTemplate: 'حفظ القالب',
    dependenciesCount: '{count} اعتماديات',
    noSystemsText: 'لا توجد أنظمة مسجلة. عرّف مكونات نظامك للبدء.',
    requiredDependencies: 'الاعتماديات المطلوبة',
    setupInstructions: 'تعليمات الإعداد',
    systemFlowchart: 'مخطط النظام / الإعداد',
    generateInstance: 'توليد نسخة',
    chooseSystemToPreview: 'اختر قالب نظام لعرض الملفات والاعتماديات وسكربتات الإعداد.',

    // Developer DNA
    loadingDna: 'جاري تحميل بصمة المطور...',
    dnaTitle: 'بصمة المطور',
    dnaSubtitle: 'ملف هندسي ومؤشرات كود مستخرجة بالذكاء',
    updateDna: 'تحديث بصمة المطور',
    favoriteTechs: 'التقنيات المفضلة',
    dnaLanguage: 'اللغة',
    dnaFramework: 'الفريمورك',
    dnaDatabase: 'قاعدة البيانات',
    engineeringStrengths: 'نقاط القوة الهندسية',
    backendSystems: 'أنظمة Backend',
    frontendInterfaces: 'واجهات Frontend',
    mobileApps: 'موبايل Flutter / Android',
    devopsCloud: 'DevOps وإعدادات السحابة',
    codeStyleScanner: 'فاحص أسلوب بصمة الكود',
    pasteToCompareStyle: 'الصق أي مقطع كود لمقارنة أسماء المتغيرات، المسافات، بنية معالجة الأخطاء، وقواعد التنسيق مع أسلوبك السابق ({style}).',
    pasteCodeHere: 'الصق مقطع الكود هنا...',
    analyzingStyle: 'جاري تحليل الأسلوب...',
    checkStyleMatch: 'فحص تطابق الأسلوب',
    styleSimilarity: 'تشابه الأسلوب',
    pasteCodeToCompare: 'الصق كوداً في اليسار لفحص درجة تشابه أسلوب التسمية.',
    errorLoadingDna: 'فشل تحميل بصمة المطور. قم بفهرسة مشاريع أولاً لحساب الملف البرمجي.',
    productivityScore: 'معدل الإنتاجية',
    productivityDescription: 'إنتاجيتك البرمجية تقع في أعلى 2% من المساهمين النخبة لهذا الأسبوع.',
    techBreakdown: 'توزيع التقنيات',
    techBreakdownSubtitle: 'توزيع هيكل العمل حسب وقت المعالجة البرمجية',
    cloudNative: 'السحابة الأصلية (Cloud Native)',
    webEngine: 'محركات الويب (Web Engine)',
    machineLearning: 'تعلم الآلة والبيانات',
    legacySupport: 'الأنظمة الموروثة / الدعم',
    topLanguages: 'أكثر اللغات استخداماً',
    skillGrowthCurve: 'منحنى نمو المهارات',
    expertiseVelocity: 'سرعة تراكم الخبرات الهندسية (آخر 6 أشهر)',
    preferredPattern: 'النمط المعماري المفضل',
    stylisticIdentity: 'الهوية الأسلوبية والتنسيق',
    dnaAnalytics: 'تحليلات البصمة',
    dnaPerformance: 'الأداء البرمجي',
    dnaSecurity: 'الجانب الأمني',
    searchInsights: 'البحث في التحليلات...',
    deployDna: 'نشر البصمة',

    // Time Machine
    january: 'يناير',
    february: 'فبراير',
    march: 'مارس',
    april: 'أبريل',
    may: 'مايو',
    june: 'يونيو',
    july: 'يوليو',
    august: 'أغسطس',
    september: 'سبتمبر',
    october: 'أكتوبر',
    november: 'نوفمبر',
    december: 'ديسمبر',
    januaryShort: 'يناير',
    februaryShort: 'فبراير',
    marchShort: 'مارس',
    aprilShort: 'أبريل',
    mayShort: 'مايو',
    juneShort: 'يونيو',
    julyShort: 'يوليو',
    augustShort: 'أغسطس',
    septemberShort: 'سبتمبر',
    octoberShort: 'أكتوبر',
    novemberShort: 'نوفمبر',
    decemberShort: 'ديسمبر',
    loadingTimeMachine: 'جاري تحميل آلة الزمن...',
    timeMachineTitle: 'آلة الزمن',
    timeMachineSubtitle: 'ارجع بالزمن لمراجعة ملفاتك القديمة والأخطاء المحلولة وأنماط العمل',
    choosePeriod: 'اختر الفترة:',
    askPastMemory: 'اسأل ذاكرتك البرمجية السابقة',
    askPastMemoryPlaceholder: 'مثال: كيف حللت مشاكل Authentication أو Supabase upload في هذه الفترة؟',
    askAi: 'اسأل الذكاء',
    timelineActivityLog: 'سجل النشاط الزمني',
    noActivitiesPeriod: 'لا توجد أنشطة في هذه الفترة. اختر تاريخاً آخر.',

    // Team Workspace
    teamWorkspace: 'مساحة الفريق',
    addingMember: 'جاري إضافة العضو...',
    addMemberSuccess: 'تمت إضافة عضو الفريق بنجاح.',
    addMemberFailed: 'فشلت الدعوة. تأكد أن البريد موجود في DevVault.',
    loadingTeamBrain: 'جاري تحميل عقل الفريق...',
    teamBrainTitle: 'عقل الفريق',
    teamBrainSubtitle: 'مساحة معرفة مشتركة للشركات وفرق البرمجة',
    inviteMember: 'إضافة عضو',
    inviteDeveloper: 'دعوة مطور إلى مساحة العمل',
    userEmail: 'بريد المستخدم',
    memberRole: 'دور العضو',
    roleMemberDesc: 'عضو، قراءة وكتابة',
    roleAdminDesc: 'مدير، صلاحية كاملة',
    addTeamMember: 'إضافة عضو الفريق',
    activeMembers: 'الأعضاء النشطون ({count})',
    removeMember: 'إزالة العضو',
    noActiveMembers: 'لا يوجد أعضاء نشطون في مساحة العمل.',
    workspacePermissions: 'صلاحيات مساحة العمل',
    rbacNotice: 'يتم التحكم في وصول أعضاء الفريق باستخدام RBAC. يمكن للمديرين رفع وحذف فهارس الكود، ويمكن للأعضاء البحث ومحادثة عقل الشركة.',
    knowledgeLock: 'قفل المعرفة: عند مغادرة أي مطور، تبقى المقاطع المفهرسة وملاحظات الأخطاء وملخصات المنطق محفوظة بأمان داخل خزنة الشركة.',

    // Billing & Plans
    stripeInitFailed: 'فشل إنشاء جلسة Stripe.',
    stripeNotConfigured: 'Stripe غير مهيأ. سيتم تطبيق ترقية محلية للتطوير بدلاً من الدفع الحقيقي.',
    upgradePlanSuccess: 'تم التحديث إلى خطة {plan} بنجاح.',
    upgradePlanFailed: 'فشلت الترقية. حاول مرة أخرى.',
    loadingBillingData: 'جاري تحميل بيانات الاشتراك...',
    pricingFreeStarter: 'البداية المجانية',
    pricingFreeStarterDesc: 'جرّب مسار فهرسة الذاكرة البرمجية',
    pricingFreeStarterPeriod: 'دائماً',
    pricingCurrentPlan: 'الخطة الحالية',
    quotaActiveRepos: 'حتى مستودعين نشطين',
    quotaCloudStorageFree: '100MB حد تخزين آمن',
    quotaRagFree: '20 سؤال RAG شهرياً',
    quotaSecretScan: 'فحص تسريب الأسرار',
    quotaLocalSearch: 'بحث محلي بالكلمات والدلالة',
    pricingProName: 'المطور المحترف',
    pricingProDesc: 'الخطة الأشهر للمطورين النشطين',
    pricingProPeriod: 'شهرياً',
    pricingProCTA: 'الترقية إلى Pro',
    quotaActiveReposPro: 'Up to 15 active repositories',
    quotaCloudStoragePro: '2GB cloud storage space',
    quotaRagPro: '250 RAG queries per month',
    quotaDependencyGraph: 'رسم اعتماديات الملفات',
    quotaProjectReplay: 'إعادة تشغيل تفاعلية للمشروع',
    quotaStyleMatch: 'مقارنة أنماط بصمة الكود',
    pricingTeamName: 'مساحة الفريق',
    pricingTeamDesc: 'مشاركة الذاكرة الهندسية للفرق الصغيرة',
    pricingTeamPeriod: 'شهرياً',
    pricingTeamCTA: 'الترقية للفريق',
    quotaActiveReposTeam: 'حتى 100 مستودع نشط',
    quotaCloudStorageTeam: '20GB مساحة تخزين للفريق',
    quotaRagTeam: '1,500 RAG queries per month',
    quotaTeamInvites: 'دعوات وعضويات للفريق',
    quotaSharedCatalog: 'كتالوج مشترك للمقاطع والأخطاء',
    quotaRbac: 'إدارة صلاحيات RBAC',
    billingAndPlans: 'الاشتراك والفوترة',
    billingMonitorDesc: 'راقب حدود الخطة، استخدام الموارد، وقم بترقية اشتراكك.',
    planLabel: 'الخطة الحالية: {plan}',
    activeReposLabel: 'المستودعات النشطة',
    reposIndexedDesc: 'المستودعات المفهرسة في البحث وجلسات المحادثة.',
    indexedCodeStorage: 'تخزين الكود المفهرس',
    fileSizeExtractedDesc: 'إجمالي حجم محتوى الملفات المستخرج من ملفات ZIP.',
    monthlyQueriesLabel: 'أسئلة الذكاء الشهرية',
    queriesRagDesc: 'الأسئلة الموجهة لمساعد RAG أو شروحات الكود هذا الشهر.',
    choosePlan: 'اختر خطتك',
    activePlan: 'الخطة النشطة',
    whatYouGet: 'ما الذي ستحصل عليه',

    // OAuth Callback
    oauthNoPayload: 'لم يتم العثور على بيانات OAuth.',
    oauthLoginFailed: 'فشل تسجيل الدخول عبر OAuth.',
    oauthCompleting: 'جاري إكمال تسجيل الدخول...',
    oauthSavingSession: 'جاري حفظ الجلسة بأمان.',

    // Spotlight / Command Palette
    explainCodePart: 'اشرح هذا الجزء من الكود: {name}',
    all: 'الكل',
    file: 'الملفات',
    codeEntity: 'الكود',
    snippet: 'المقاطع',
    errorSolutionFilter: 'الأخطاء',
    searchPalettePlaceholder: 'ابحث في الملفات، الدوال، الأخطاء، والمقاطع...',
    searchPaletteGuide: 'ابحث داخل الملفات المفهرسة، عناصر الكود، المقاطع، وحلول الأخطاء.',
    matchScore: 'تطابق {score}%',
    open: 'فتح',
    noMatchResults: 'لا توجد نتائج مطابقة في ذاكرتك البرمجية.',
    smartSearchReady: 'البحث الهندسي الذكي جاهز.',
    smartSearchInstruction: 'اكتب للبحث في أجزاء الكود، وصف الملفات، الأخطاء المسجلة أو المقاطع المحفوظة.',

    // Chat Page
    reachedRagLimit: 'لقد وصلت إلى الحد الشهري لأسئلة الذكاء. يرجى ترقية اشتراكك للمتابعة.',
    chatErrorOccurred: 'فشل معالجة سؤال المحادثة. تحقق من الاتصال وحاول مرة أخرى.',
    loadingChatSpace: 'جاري تحميل مساحة عمل محادثة الذكاء...',
    newChat: 'محادثة جديدة',
    projectScope: 'سياق المشروع',
    searchAllRepos: 'البحث في كل المستودعات',
    loadedSources: 'المصادر المحملة',
    openSourceDetails: 'افتح {path} من تفاصيل المشروع لمراجعة المصدر الكامل.',
    chooseProjectToLoadFiles: 'اختر مشروعاً لتحميل الملفات إلى سياق الذكاء.',
    recentChats: 'المحادثات الأخيرة',
    noRecentChats: 'لا توجد محادثات أخيرة.',
    upgradeSubscription: 'ترقية الاشتراك',
    aiAssistant: 'مساعد DevVault بالذكاء',
    askAnythingRepo: 'اسأل أي شيء حول مشاريعك المرفوعة ومعرفتك البرمجية السابقة.',
    askAiAboutRepos: 'اسأل DevVault AI عن مشاريعك البرمجية...',
    codeWorkspace: 'مساحة الكود الذكية',
    contextAwareCodePreview: 'معاينة الكود الذكية بالسياق',
    askQuestionToPreview: 'اسأل سؤالاً أو افتح مصدراً مرجعياً. سيعرض DevVault الكود والملخصات وملاحظات التحسين هنا.',
    codeExplanation: 'شرح الكود',
    dependencies: 'الاعتماديات',
    optimizations: 'التحسينات',
    securityAnalysisLabel: 'تحليل الأمان',
    loadedSourcesCount: 'المصادر المحملة: {count}',
    // Notifications System
    notifications: 'الإشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    noNotifications: 'لا توجد إشعارات جديدة',
    deleteNotification: 'حذف الإشعار',
    clearAll: 'مسح الكل',
    notificationSuccess: 'نجاح',
    notificationInfo: 'معلومات',
    notificationWarning: 'تحذير',
    notificationError: 'خطأ'
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const storedLang = localStorage.getItem('language') as Language;
    if (storedLang === 'en' || storedLang === 'ar') {
      setLanguage(storedLang);
      updateDocumentAttributes(storedLang);
    } else {
      updateDocumentAttributes('en');
    }

    // Apply stored accent color
    const storedAccent = localStorage.getItem('accentColor') || 'blue';
    document.documentElement.classList.remove('accent-blue', 'accent-purple', 'accent-amber', 'accent-green');
    document.documentElement.classList.add(`accent-${storedAccent}`);
  }, []);

  const updateDocumentAttributes = (lang: Language) => {
    const dir: Direction = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
    if (lang === 'en') {
      document.documentElement.classList.add('ltr-layout');
      document.documentElement.classList.remove('rtl-layout');
    } else {
      document.documentElement.classList.add('rtl-layout');
      document.documentElement.classList.remove('ltr-layout');
    }
  };

  const toggleLanguage = () => {
    const nextLang: Language = language === 'ar' ? 'en' : 'ar';
    setLanguage(nextLang);
    localStorage.setItem('language', nextLang);
    updateDocumentAttributes(nextLang);
  };

  const t = (key: string, variables?: Record<string, string | number>): string => {
    let text = translations[language][key] || translations['en'][key] || key;
    if (variables) {
      Object.entries(variables).forEach(([k, v]) => {
        text = text.replace(new RegExp(`{${k}}`, 'g'), String(v));
      });
    }
    return text;
  };

  const dir: Direction = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, dir, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
