import { Response } from 'express';
import mongoose from 'mongoose';
import { AuthenticatedRequest } from '../middleware/auth';
import { File as DBFile, Project, Activity, CodeEntity, ErrorSolution, ReusableSystem, Workspace } from '../models';

const accessibleProjectFilter = async (userId: string, projectId: string) => {
  const workspaces = await Workspace.find({ 'members.userId': userId }, '_id').lean();
  return {
    _id: projectId,
    $or: [
      { userId },
      { workspaceId: { $in: workspaces.map((workspace) => workspace._id) } },
    ],
  };
};

export const getProjectReplay = async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.user) return res.status(401).json({ error: 'Unauthorized.' });
    const { id } = req.params;
    if (!mongoose.Types.ObjectId.isValid(id)) {
      return res.status(400).json({
        error: 'Invalid projectId.',
        code: 'INVALID_OBJECT_ID',
      });
    }

    const project = await Project.findOne(await accessibleProjectFilter(req.user.id, id));
    if (!project) return res.status(404).json({ error: 'Project not found.' });

    const files = await DBFile.find({ projectId: id }).sort({ createdAt: 1 });
    const errors = await ErrorSolution.find({ projectId: id, userId: req.user.id }).sort({ createdAt: 1 });

    const timeline: any[] = [];
    const projectCreated = new Date(project.uploadedAt || project.createdAt);

    // Initialization Milestone
    timeline.push({
      day: projectCreated.toLocaleDateString(),
      title: 'Initialize repository',
      description: `Project initialized. Tech stack registered: ${project.language || 'Generic'} using ${project.framework || 'Vanilla'} framework.`,
      files: [],
    });

    if (files.length > 0) {
      // Define Data Schema Layer
      const modelFiles = files.filter(f => f.path.toLowerCase().includes('model') || f.path.toLowerCase().includes('schema'));
      if (modelFiles.length > 0) {
        timeline.push({
          day: new Date(modelFiles[0].createdAt || projectCreated).toLocaleDateString(),
          title: 'Define Data Schema Layer',
          description: `Imported database mapping files. Scanned DB type: ${project.database || 'in-memory'}.`,
          files: modelFiles.map(f => f.path),
        });
      }

      // Route Controllers
      const controllerFiles = files.filter(f => f.path.toLowerCase().includes('controller') || f.path.toLowerCase().includes('route'));
      if (controllerFiles.length > 0) {
        timeline.push({
          day: new Date(controllerFiles[0].createdAt || projectCreated).toLocaleDateString(),
          title: 'Establish Routing & Controller flow',
          description: 'Linked Express routers and application controller pathways.',
          files: controllerFiles.map(f => f.path),
        });
      }
    }

    // Exception resolutions
    if (errors.length > 0) {
      errors.forEach((err) => {
        timeline.push({
          day: new Date(err.solvedAt || err.createdAt).toLocaleDateString(),
          title: `Resolved Bug: ${err.title}`,
          description: `Logged exception fix. Cause: ${err.cause}`,
          files: [],
        });
      });
    }

    return res.status(200).json({ timeline });
  } catch {
    return res.status(500).json({
      error: 'An unexpected project replay error occurred.',
      code: 'PROJECT_REPLAY_FAILED',
    });
  }
};

export const generateStandup = async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.user) return res.status(401).json({ error: 'Unauthorized.' });

    // Look at activities from past 24 hours
    const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const activities = await Activity.find({
      userId: req.user.id,
      createdAt: { $gte: yesterday },
    });

    let yesterdayActions = '';
    
    if (activities.length > 0) {
      yesterdayActions = activities.map(a => `- ${a.action} (${a.entityType})`).join('\n');
    } else {
      yesterdayActions = '- No developer activities recorded in the last 24 hours. (Upload a project or log an error to see daily updates here.)';
    }

    const standupReport = `### 📝 Daily Standup Report
Generated by DevVault AI for ${req.user.email.split('@')[0]}

**Yesterday (Accomplished):**
${yesterdayActions}

**Today (Focusing on):**
- Ongoing system code analysis and file index validation
- Address pending issues and security checks

**Blockers:**
- None.`;

    return res.status(200).json({ standup: standupReport });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
};

export const getHiddenKnowledge = async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.user) return res.status(401).json({ error: 'Unauthorized.' });
    const userId = req.user.id;

    const projects = await Project.find({ userId }, '_id');
    const projectIds = projects.map((project) => project._id);

    // Scan only this user's projects for repeated code entities.
    const entities = await CodeEntity.find({ projectId: { $in: projectIds } }).populate('projectId');
    const nameCountMap: Record<string, any[]> = {};

    for (const ent of entities) {
      if (ent.type === 'class' || ent.type === 'function') {
        const key = ent.name.toLowerCase();
        if (!nameCountMap[key]) nameCountMap[key] = [];
        nameCountMap[key].push(ent);
      }
    }

    const repeats: { title: string; description: string; count: number }[] = [];
    
    Object.entries(nameCountMap).forEach(([name, matches]) => {
      // If same name is defined in more than 1 file
      if (matches.length > 1) {
        const projectNames = Array.from(new Set(matches.map(m => m.projectId?.name || 'Generic')));
        repeats.push({
          title: `Repeated Code Block: "${name}"`,
          description: `You have built this code element in ${matches.length} files across projects: ${projectNames.join(', ')}.`,
          count: matches.length,
        });
      }
    });

    return res.status(200).json({ repeats });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
};

export const getOpportunity = async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.user) return res.status(401).json({ error: 'Unauthorized.' });
    const userId = req.user.id;

    const projects = await Project.find({ userId });
    
    let recommendation = 'Upload additional codebases to extract custom SaaS bundle opportunities.';
    let marketSuggestions: any[] = [];
    
    if (projects.length > 0) {
      const countCRM = projects.filter(p => p.name.toLowerCase().includes('crm')).length;
      const countEcom = projects.filter(p => p.name.toLowerCase().includes('shop') || p.name.toLowerCase().includes('ecom')).length;
      
      recommendation = `You have uploaded ${projects.length} repository templates. Consider compiling reusable stack blueprints to share.`;
      
      if (countCRM > 1) {
        recommendation = `You have built ${countCRM} CRM dashboards. You can package these modules into a reusable Customer Management SaaS boiler kit.`;
      } else if (countEcom > 1) {
        recommendation = `You have constructed ${countEcom} Ecommerce APIs. We recommend compiling a reusable Stripe Payment + checkout blueprint.`;
      }

      // Query actual reusable systems
      const systems = await ReusableSystem.find({ userId });
      marketSuggestions = systems.map(s => ({
        title: s.name,
        price: '$15',
        installs: 0
      }));
    }

    return res.status(200).json({
      projectsCount: projects.length,
      recommendation,
      marketSuggestions
    });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
};

export const getRecentActivities = async (req: AuthenticatedRequest, res: Response) => {
  try {
    if (!req.user) return res.status(401).json({ error: 'Unauthorized.' });
    
    const activities = await Activity.find({ userId: req.user.id })
      .sort({ createdAt: -1 })
      .limit(10);

    return res.status(200).json({ activities });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
};
